SHELL = /usr/bin/bash
CC = g++

.SUFFIXES: .cpp
4-1: 4-1.cpp
	$(CC) -o 4-1 4-1.cpp
4-2_LFU: 4-2_LFU.cpp
	$(CC) -o 4-2_LFU 4-2_LFU.cpp
4-2_LRU: 4-2_LRU.cpp
	$(CC) -o 4-2_LRU 4-2_LRU.cpp

clean:
	rm -f 4-1 4-2_LFU 4-2_LRU